# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HuanXinChatDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HuanXinChatDemo

  pod 'HyphenateFullSDK'
  pod 'SDAutoLayout', '~> 2.1.7'

end
